# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Tom Griesler"
description              : "Personal site"
url                      : https://tomgriesler.github.io
baseurl                  : ""
repository               : "tomgriesler.github.io"
breadcrumbs              : false
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : tomgriesler
og_image                 :
social:
  type                   : Person
  name                   : Tom Griesler
  links: []


# Analytics
analytics:
  provider               : false


# Site Author
author:
  name             : "Tom Griesler"
  avatar           : "profile_picture.jpeg"
  bio              : "BME PhD candidate at the University of Michigan"
  location         : "Ann Arbor, MI"
  googlescholar    : "https://scholar.google.com/citations?user=SGiGw1cAAAAJ&hl=en&oi=sra"
  email            : "tomgr@med.umich.edu"
  github           : "tomgriesler"
  linkedin         : "tomgriesler"
  orcid            : "https://orcid.org/0009-0003-3777-5483"
  # twitter          : "tomgriesler"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
# Collections (disabled for minimal site)
collections: {}


# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: America/Detroit


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
